//! Phase S1.2 — off-circuit **Poseidon1** reference hash over the Pallas base
//! field `Fp`.
//!
//! This is the field-element hash that the note commitment (S1.3), nullifier
//! derivation (S1.4), and incremental Merkle tree (S1.6) will be built on. It is
//! the *off-circuit reference* implementation; the in-circuit sponge (S2) must
//! share **byte-identical round constants + MDS** with this one so the two are
//! mutually verifiable.
//!
//! # Field
//!
//! The hash operates over **`pasta_curves::pasta::Base`** (`Fp`, the Pallas base
//! field), *not* the scalar field `Fq`. The Halo2 circuit is `Circuit<Fp>`, so
//! every field-element primitive (sponge, tree leaves, commitments) lives in
//! `Fp` — this corrects the plan's loose `Fr`.
//!
//! # S-box exponent: `x^7`, not `x^5`
//!
//! Poseidon's S-box is `x ↦ x^α`, which is a permutation of `Fp` only when
//! `gcd(α, p-1) = 1`. For the Pallas base field `p ≡ 1 (mod 5)`, so
//! `gcd(5, p-1) = 5` and **`x^5` is NOT a bijection** — an `x^5` S-box would
//! collapse the permutation. The smallest valid exponent is `3` (too weak for a
//! 255-bit field); `7` is the canonical fallback used by gnark / plonky and gives
//! a strong, invertible S-box. This implementation therefore uses **α = 7**.
//!
//! # Parameters (Grain-LFSR derived)
//!
//! The round constants and MDS matrix are generated by the canonical,
//! reproducible Grain-LFSR method (the Poseidon paper's algorithm, as used by
//! gnark / light-poseidon / plonky):
//!
//! * Grain LFSR taps `[0, 13, 23, 38, 51, 62]`, 80-bit seed encoding
//!   `(field_type=1, sbox=0, n=255, t=5, R_F=8, R_P=46, 30 ones)`, 160 warm-up
//!   clocks.
//! * State width **t = 5**, `R_F = 8` full rounds, `R_P = 46` partial rounds.
//! * Round constants: `(R_F + R_P) · t = 54 · 5 = 270` field elements, drawn in
//!   order from the Grain stream.
//! * **Cauchy** MDS: `M[i][j] = 1 / (xs[i] + ys[j])` over 2t distinct Grain-
//!   sampled elements (xs = first t, ys = last t), drawn by continuing the SAME
//!   Grain stream after the round constants.
//!
//! # Sponge convention
//!
//! Rate `r = t - 1 = 4`, capacity `c = 1`. Input is padded with **Pad\*10\***:
//! append a single `1`, then zeros to a multiple of `r`. Absorb `r` elements into
//! the first `r` lanes, permute. After the last permutation, **squeeze lane
//! `t-1`** (the capacity lane) → one `Fp` output. Pad\*10\* is length-sensitive:
//! `hash([a]) ≠ hash([a, 0])`, which guards against a length-blind hash.
//!
//! Poseidon deliberately does **not** implement the SHA-256 `HashProvider` trait
//! (`crypto.rs:645`): its I/O is `&[Fp]`, not `&[u8]`, so the field types are
//! incompatible.

use once_cell::sync::Lazy;

use ff::{Field, PrimeField};
use pasta_curves::pallas::Base as Fp;

/// State width `t`.
const T: usize = 5;
/// S-box exponent. `x^7` — required because `gcd(5, p-1) = 5` over Pallas `Fp`
/// (see module docs); `x^7` is a bijection.
const ALPHA_EXP: u64 = 7;
/// Total full rounds `R_F` (split as `R_F / 2` before and after the partial
/// rounds).
const R_F: usize = 8;
/// Partial rounds `R_P`.
const R_P: usize = 46;
/// Sponge rate `r = t - 1`.
const RATE: usize = T - 1;
/// Bit length of the Pallas base field prime `p`.
const N_BITS: usize = 255;

/// A round-constants table: one `[Fp; T]` per round, in round order.
type RcTable = [[Fp; T]; R_F + R_P];
/// The 5×5 Cauchy MDS matrix.
type MdsMatrix = [[Fp; T]; T];

/// Pre-computed Poseidon parameters: round constants then the Cauchy MDS matrix.
///
/// Generated once (lazily) from a single Grain-LFSR stream: the round constants
/// are drawn first, then the MDS generation **continues the same stream**.
static PARAMS: Lazy<Params> = Lazy::new(|| {
    let mut grain = Grain::new();
    let rc = round_constants(&mut grain);
    let mds = cauchy_mds(&mut grain);
    Params { rc, mds }
});

struct Params {
    rc: RcTable,
    mds: MdsMatrix,
}

/// The Grain-LFSR used to derive Poseidon round constants + MDS (index-pointer
/// form; reads the feedback taps relative to the current head `p`).
struct Grain {
    /// 80-bit shift register.
    s: [u8; 80],
    /// Read/write pointer (the current head position).
    p: usize,
}

impl Grain {
    fn new() -> Self {
        fn bits(val: u64, w: usize) -> Vec<u8> {
            (0..w).rev().map(|i| ((val >> i) & 1) as u8).collect()
        }
        // 80-bit seed: field_type(1)=1, sbox(0)=0, n=255, t=5, R_F=8, R_P=46, 30 ones.
        let mut s: Vec<u8> = Vec::with_capacity(80);
        s.extend_from_slice(&bits(1, 2)); // field_type: GF(p)
        s.extend_from_slice(&bits(0, 4)); // sbox index
        s.extend_from_slice(&bits(N_BITS as u64, 12)); // n
        s.extend_from_slice(&bits(T as u64, 12)); // t
        s.extend_from_slice(&bits(R_F as u64, 10)); // R_F
        s.extend_from_slice(&bits(R_P as u64, 10)); // R_P
        s.extend_from_slice(&[1u8; 30]); // ones
        assert_eq!(s.len(), 80, "Grain seed must be 80 bits");
        let s: [u8; 80] = s
            .try_into()
            .expect("80-bit Grain seed — the assertions above guarantee this");
        let mut g = Grain { s, p: 0 };
        // 160 warm-up clocks before any output.
        for _ in 0..160 {
            g.tick();
        }
        g
    }

    fn mix(&self, p: usize) -> u8 {
        let s = self.s;
        // Feedback taps relative to the current head `p`.
        s[(p + 0) % 80]
            ^ s[(p + 13) % 80]
            ^ s[(p + 23) % 80]
            ^ s[(p + 38) % 80]
            ^ s[(p + 51) % 80]
            ^ s[(p + 62) % 80]
    }

    /// Advance the register by one clock; return the feedback bit that is
    /// clocked into the head.
    fn tick(&mut self) -> u8 {
        let p = self.p;
        let nb = self.mix(p);
        self.s[p] = nb; // write feedback into the head, then shift.
        self.p = (p + 1) % 80;
        nb
    }

    /// Next keystream bit: clock twice, return the second bit iff the first is 1
    /// (otherwise retry).
    fn next_bit(&mut self) -> u8 {
        loop {
            let a = self.tick();
            let b = self.tick();
            if a == 1 {
                return b;
            }
        }
    }

    /// Sample one field element: draw `N_BITS` bits and form the integer
    /// `v = int(bits, 2)` (first Grain bit is the most significant, at absolute
    /// bit `N_BITS - 1 = 254`), then take its canonical representative via
    /// `ff::PrimeField::from_repr`, rejecting (`>= p`) by redrawing — identical to
    /// the reference `int(bits, 2) < p` rejection.
    ///
    /// `from_repr` expects the **little-endian** repr, so each Grain bit `i` is
    /// placed at absolute bit position `254 - i` (not `255 - i`): placing it one
    /// bit higher would shift the whole value left by one and produce a
    /// different constant stream.
    fn field_element(&mut self) -> Fp {
        loop {
            let mut repr = [0u8; 32];
            for i in 0..N_BITS {
                let ap = (N_BITS - 1) - i; // 254 down to 0
                repr[ap / 8] |= (self.next_bit() as u8) << (ap % 8);
            }
            let opt = Fp::from_repr(repr);
            let mut v = Fp::zero();
            if bool::from(opt.is_some()) {
                // < p, so this is the canonical representative: extract it.
                opt.map(|x| {
                    v = x;
                });
                return v;
            }
            // else value >= p: reject and redraw.
        }
    }
}

/// Draw `(R_F + R_P) · t` field elements from the Grain stream and lay them out
/// as one `[Fp; T]` per round.
fn round_constants(grain: &mut Grain) -> RcTable {
    let n = (R_F + R_P) * T;
    let mut raw = Vec::with_capacity(n);
    for _ in 0..n {
        raw.push(grain.field_element());
    }
    let mut table = [[Fp::zero(); T]; R_F + R_P];
    for (row, chunk) in table.iter_mut().zip(raw.chunks(T)) {
        row.copy_from_slice(chunk);
    }
    table
}

/// Build the Cauchy MDS matrix `M[i][j] = 1 / (xs[i] + ys[j])` by continuing the
/// same Grain stream after the round constants.
fn cauchy_mds(grain: &mut Grain) -> MdsMatrix {
    loop {
        // Sample 2t distinct field elements.
        let mut rand = Vec::with_capacity(2 * T);
        while rand.len() < 2 * T {
            let v = grain.field_element();
            if !rand.contains(&v) {
                rand.push(v);
            }
        }
        let xs = &rand[..T];
        let ys = &rand[T..];
        // Reject if any xs[i] + ys[j] ≡ 0 (would make the inverse undefined).
        let mut valid = true;
        for (i, x) in xs.iter().enumerate() {
            for (j, y) in ys.iter().enumerate() {
                if bool::from((*x + *y) == Fp::zero()) {
                    valid = false;
                    break;
                }
            }
            if !valid {
                break;
            }
        }
        if !valid {
            continue;
        }
        let mut mds = [[Fp::zero(); T]; T];
        for (i, row) in mds.iter_mut().enumerate() {
            for (j, cell) in row.iter_mut().enumerate() {
                let x = xs[i] + ys[j];
                // x is nonzero here (checked above), so its inverse is defined.
                let mut inv_val = Fp::zero();
                x.invert().map(|v| {
                    inv_val = v;
                });
                *cell = inv_val;
            }
        }
        return mds;
    }
}

/// S-box `x ↦ x^7`. `x^7 = x^4 · x^2 · x`; two squarings + two multiplies.
fn sbox(x: Fp) -> Fp {
    let x2 = x.square();
    let x4 = x2.square();
    x4 * x2 * x
}

/// Multiply the state by the MDS matrix: `out[i] = Σ_j mds[i][j] · state[j]`.
fn matvec(mds: &MdsMatrix, state: &[Fp; T]) -> [Fp; T] {
    let mut out = [Fp::zero(); T];
    for (i, out_cell) in out.iter_mut().enumerate() {
        let mut acc = Fp::zero();
        for j in 0..T {
            acc += mds[i][j] * state[j];
        }
        *out_cell = acc;
    }
    out
}

/// Poseidon1 permutation: `R_F/2` full rounds → `R_P` partial rounds → `R_F/2`
/// full rounds. Every round adds its round constants, applies the S-box (all
/// lanes for full rounds, only lane 0 for partial rounds), then multiplies by
/// the MDS matrix.
fn permute(state: &mut [Fp; T], params: &Params) {
    let rc = &params.rc;
    let mds = &params.mds;
    let half = R_F / 2;
    let mut idx = 0;

    // Initial full rounds.
    for _ in 0..half {
        for k in 0..T {
            state[k] += rc[idx][k];
        }
        for k in 0..T {
            state[k] = sbox(state[k]);
        }
        *state = matvec(mds, state);
        idx += 1;
    }
    // Partial rounds.
    for _ in 0..R_P {
        for k in 0..T {
            state[k] += rc[idx][k];
        }
        state[0] = sbox(state[0]);
        *state = matvec(mds, state);
        idx += 1;
    }
    // Terminal full rounds.
    for _ in 0..half {
        for k in 0..T {
            state[k] += rc[idx][k];
        }
        for k in 0..T {
            state[k] = sbox(state[k]);
        }
        *state = matvec(mds, state);
        idx += 1;
    }
}

/// Absorb the input with Pad\*10\* and return the post-permutation state — the
/// last permutation's full 5-lane output. Exposed for diffusion testing.
fn sponge_perm_state(inputs: &[Fp]) -> [Fp; T] {
    let params = &PARAMS;
    let mut state = [Fp::zero(); T];
    let mut padded = Vec::with_capacity(inputs.len() + 2);
    padded.extend_from_slice(inputs);
    padded.push(Fp::one()); // Pad*: terminate with a 1
    while padded.len() % RATE != 0 {
        padded.push(Fp::zero());
    }
    for chunk in padded.chunks(RATE) {
        for i in 0..chunk.len() {
            state[i] += chunk[i];
        }
        permute(&mut state, params);
    }
    state
}

/// Absorb the input and **squeeze** the capacity lane (`t - 1`): one `Fp` output.
fn sponge_hash(inputs: &[Fp]) -> Fp {
    sponge_perm_state(inputs)[T - 1]
}

/// Trait for a Poseidon hash over the Pasta base field.
///
/// Deliberately NOT the SHA-256 `HashProvider` trait (`crypto.rs:645`): its I/O
/// is `&[Fp]`, not `&[u8]`, so the field types are incompatible.
pub trait PoseidonHasher {
    fn hash(&self, inputs: &[Fp]) -> Fp;
}

/// Zero-sized Poseidon hash provider over the Pallas base field. `new()` ==
/// `default()` — the implementation is a stateless free function.
#[derive(Debug, Clone, Copy, Default)]
pub struct PoseidonHashProvider;

impl PoseidonHasher for PoseidonHashProvider {
    fn hash(&self, inputs: &[Fp]) -> Fp {
        sponge_hash(inputs)
    }
}

/// Off-circuit Poseidon1 reference: `&[Fp] → Fp` over the Pallas base field.
///
/// See the module docs for the parameter set, S-box exponent, and sponge
/// convention. The in-circuit sponge (S2) must share these exact constants.
pub fn poseidon_hash(inputs: &[Fp]) -> Fp {
    PoseidonHashProvider.hash(inputs)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The anchor: known-answer vectors from the independent, authoritative
    /// Python Poseidon1 reference (single Grain stream, α=7, t=5, R_F=8,
    /// R_P=46, Pad10* sponge). Any wrong round constant, MDS entry, round count,
    /// exponent, or sponge convention makes this fail — the primary discriminator.
    #[test]
    fn poseidon_kat() {
        // Expected outputs as 32-byte big-endian canonical `to_bytes()` of Fp.
        // Cross-checked against the independent Python Poseidon1 reference
        // (/tmp/oracle.py): single Grain stream, alpha=7, t=5, R_F=8, R_P=46,
        // Cauchy MDS over the Pallas base field Fp, Pad10* sponge (absorb rate
        // = t-1 cells, squeeze capacity lane T-1). Each input below is chosen to
        // be expressible exactly in Rust so the oracle output and the Rust input
        // unambiguously agree.
        let cases: &[(&str, Vec<Fp>, [u8; 32])] = &[
            ("empty", vec![], [
                0x05,0x71,0xf4,0xbd,0x58,0x80,0x88,0x77,
                0xe3,0xca,0xb8,0x10,0xd5,0x73,0xfd,0xf2,
                0xe9,0xa3,0x59,0xa5,0xb9,0x6c,0xde,0xd2,
                0xa0,0xdd,0xd7,0x9d,0xce,0x64,0x2c,0x50,
            ]),
            ("zero", vec![Fp::from(0u64)], [
                0x0c,0xae,0xd1,0xe5,0x64,0xbc,0xab,0x5b,
                0x39,0x24,0xba,0x12,0xa2,0x3f,0xe3,0x10,
                0x61,0x79,0x12,0x63,0xd7,0x29,0x6c,0x4f,
                0x47,0x2f,0x1c,0x71,0x9b,0x08,0x52,0xb6,
            ]),
            ("one", vec![Fp::from(1u64)], [
                0x3b,0x96,0x3c,0x99,0xf5,0x1b,0x97,0xc0,
                0x72,0xa7,0x7d,0x90,0x55,0xb2,0x1c,0x40,
                0x4b,0x48,0xec,0xd7,0x9b,0xe8,0x9e,0xd2,
                0x96,0x4d,0x76,0x95,0xdf,0xb4,0x4e,0xdf,
            ]),
            ("two", vec![Fp::from(1u64), Fp::from(2u64)], [
                0x36,0x99,0x85,0x97,0x73,0x96,0x22,0x64,
                0xb7,0x52,0xc8,0x17,0x2f,0xfa,0xd6,0xd0,
                0x3f,0x97,0x9f,0x53,0xfc,0xcb,0x6a,0x36,
                0xd3,0xa4,0xe4,0xf9,0x30,0xc5,0xbe,0x10,
            ]),
            ("five", vec![Fp::from(1u64), Fp::from(2u64), Fp::from(3u64), Fp::from(4u64), Fp::from(5u64)], [
                0x0b,0xbc,0x69,0x08,0xad,0xba,0x6a,0xb7,
                0x87,0xc5,0xb8,0xf7,0xc4,0x03,0xcb,0x79,
                0xed,0x05,0x95,0x12,0x99,0x8a,0xee,0x45,
                0x94,0x1e,0xcf,0xe2,0x72,0x07,0x13,0x61,
            ]),
            ("with_zero", vec![Fp::from(1u64), Fp::from(0u64)], [
                0x37,0x39,0x23,0xea,0x0d,0x95,0xa6,0x9a,
                0xa8,0x08,0x06,0xd8,0xe0,0x24,0xda,0x0f,
                0x26,0x14,0xf4,0xb5,0x82,0x77,0x3d,0xf3,
                0xa6,0x43,0x8c,0xd7,0x20,0x4b,0xa9,0xa5,
            ]),
            ("big", vec![
                Fp::zero() - Fp::one(), // P - 1, the largest field element
                Fp::zero(),
                Fp::from(12345u64),
                Fp::from(7u64),
                Fp::from(8u64),
            ], [
                0x28,0x0c,0x97,0x7f,0x29,0x8c,0x57,0xc7,
                0x0f,0x49,0x2b,0x27,0xd5,0x99,0x75,0x91,
                0x78,0x5a,0x85,0x4e,0x3d,0xa6,0x2c,0xfa,
                0x4c,0xdb,0x8a,0x6b,0xcc,0x80,0x13,0x2f,
            ]),
            ("zeros3", vec![Fp::from(0u64), Fp::from(0u64), Fp::from(0u64)], [
                0x2b,0xe6,0x5d,0xbd,0x7f,0x33,0x53,0xdd,
                0x5d,0xa2,0x47,0x10,0x47,0xb3,0xff,0xf2,
                0x34,0x2d,0xf9,0xdc,0xf3,0x7b,0x10,0xce,
                0x8d,0x93,0xd8,0xf7,0x5b,0x87,0xc0,0xc0,
            ]),
        ];
        for (name, inputs, expected) in cases {
            // `to_repr()` yields the canonical little-endian repr; reverse to
            // big-endian so it matches the oracle's `format(h, '064x')` encoding.
            let mut got = poseidon_hash(inputs).to_repr();
            got.reverse();
            assert_eq!(
                got, *expected,
                "Poseidon KAT mismatch for `{name}`\n  got     = 0x{}\n  expected= 0x{}",
                hex(&got),
                hex(expected),
            );
        }
    }

    fn hex(bytes: &[u8; 32]) -> String {
        let mut s = String::with_capacity(64);
        for b in bytes {
            s.push_str(&format!("{:02x}", b));
        }
        s
    }

    /// Deterministic: identical inputs → identical output across repeated calls.
    #[test]
    fn poseidon_is_deterministic() {
        let inputs = vec![Fp::from(42), Fp::from(1), Fp::from(7), Fp::zero()];
        let a = poseidon_hash(&inputs);
        let b = poseidon_hash(&inputs);
        let c = poseidon_hash(&inputs);
        assert_eq!(a, b);
        assert_eq!(b, c);
    }

    /// Discriminator (tamper): flipping one input element changes the output.
    #[test]
    fn poseidon_tamper_changes_output() {
        let inputs = vec![Fp::from(1), Fp::from(2), Fp::from(3)];
        let mut tampered = inputs.clone();
        tampered[1] += Fp::one(); // flip one input element
        assert_ne!(
            poseidon_hash(&inputs),
            poseidon_hash(&tampered),
            "mutating one input must change the hash"
        );
    }

    /// Length sensitivity: Pad10* makes `hash([a]) ≠ hash([a, 0])`. A
    /// length-blind hash (naive zero-padding) would collide these.
    #[test]
    fn poseidon_length_sensitive() {
        let a = Fp::from(12345);
        assert_ne!(
            poseidon_hash(&[a]),
            poseidon_hash(&[a, Fp::zero()]),
            "Pad10* must make differing-length inputs hash differently"
        );
        assert_ne!(
            poseidon_hash(&[a]),
            poseidon_hash(&[a, Fp::zero(), Fp::zero()]),
        );
        assert_ne!(
            poseidon_hash(&[a, Fp::zero()]),
            poseidon_hash(&[a, Fp::zero(), Fp::zero()]),
        );
    }

    /// Diffusion: perturbing a single input lane must propagate to *several*
    /// output lanes of the post-permutation state. A one-round or under-rounded
    /// permutation would leave other lanes untouched.
    #[test]
    fn poseidon_diffuses_across_lanes() {
        let inputs = vec![Fp::from(1), Fp::from(2), Fp::from(3), Fp::from(4)];
        let mut tampered = inputs.clone();
        tampered[0] += Fp::one();

        let state0 = sponge_perm_state(&inputs);
        let state1 = sponge_perm_state(&tampered);

        // At least 3 of the 5 output lanes must differ (a real permutation
        // diffuses; a weak one would not).
        let diff_count = state0.iter().zip(state1.iter()).filter(|(a, b)| a != b).count();
        assert!(
            diff_count >= 3,
            "expected diffusion into >=3 lanes, only {diff_count} changed"
        );
        // And of course the squeezed capacity lane differs too.
        assert_ne!(state0[T - 1], state1[T - 1]);
    }

    /// Discriminator proof: the KAT depends on a *non-trivial* round count and
    /// exponent. Temporarily dropping a partial round (or flipping the S-box to a
    /// no-op) must make the anchored KAT fail — proving the test pins the
    /// parameters rather than passing trivially.
    #[test]
    fn poseidon_kat_pins_parameters() {
        // Independent anchor check (not via the `poseidon_kat` cases loop): the
        // hash of `[1]` must equal the oracle-derive `one` value. This pins the
        // round constants + round count + exponent directly against the KAT.
        // Sensitivity is proven by a temporary revert of one partial round (or
        // the round-constant table) — see plan Verify step 4 — which must make
        // this assertion (and `poseidon_kat`) fail.
        let mut got = poseidon_hash(&[Fp::one()]).to_repr();
        got.reverse(); // little-endian repr -> big-endian for oracle comparison
        let expected: [u8; 32] = [
            0x3b,0x96,0x3c,0x99,0xf5,0x1b,0x97,0xc0,
            0x72,0xa7,0x7d,0x90,0x55,0xb2,0x1c,0x40,
            0x4b,0x48,0xec,0xd7,0x9b,0xe8,0x9e,0xd2,
            0x96,0x4d,0x76,0x95,0xdf,0xb4,0x4e,0xdf,
        ];
        assert_eq!(
            got, expected,
            "the `[1]` anchor must match the oracle KAT",
        );
    }
}
